customer: forsale
appName: ping-pong
env: staging
replicaCount: 1

image:
  repository: ping-pong
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: LoadBalancer
  port: 80
  targetPort: 80
