apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.appName }}"
  namespace: "{{ .Values.namespace }}"
  labels:
    customer: "{{ .Values.customer }}"
    app: "{{ .Values.appName }}"
    environment: "{{ .Values.env }}"
spec:
    selector:
      app: "{{ .Values.appName }}"
    type: "{{ .Values.service.type }}"
    ports:
      - name: http
        protocol: TCP
        port: {{ .Values.service.port }}
        targetPort: {{ .Values.service.targetPort }}