version: 0.2
phases:
  install:
    commands:
      - curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
      - chmod 700 get_helm.sh
      - ./get_helm.sh
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=${ECR_REPO_URL}
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - echo configuring kubectl
      - aws eks update-kubeconfig --name $EKS_CLUSTER_NAME
      - kubectl config set-context --current --namespace=$EKS_NAMESPACE
  build:
    commands:
      - echo Deployment started on `date`
      - helm upgrade --install --force --wait --timeout 600 --set image.repository=$REPOSITORY_URI,image.tag=$IMAGE_TAG $HELM_RELEASE_NAME $HELM_CHART_PATH
      - echo Deployment finished on `date`
